[phases.setup]
nixpkgs = ['pkgs...']
packages = ['nodejs_20', 'pnpm']

[phase.install]
cmds = ['pnpm install --frozen-lockfile']

[phase.build]
cmds = ['pnpm run build']

[phase.start]
cmd = ['pnpm run start']
